@startuml
actor Пользователь
participant "Приложение \nКинокасса" as Client_app
participant "Сервер \nавторизации" as Auth
participant "Календарь/сервер ресурсов" as Calendar

Пользователь -> Client_app: 1. Добавить событие в календарь
note right of Client_app
    Предоставляете ли вы доступ "Приложению Кинокасса" к следующим ресурсам:
    - "Календарь"
    "Да"  "Нет"
end note
Client_app -> Client_app: Генерирует ссылку на страницу авторизации
Client_app -> Пользователь: 2. Запрос кода доступа (перенаправление на страницу авторизации)
note right of Пользователь
 Если приложение нативное, то откроется ситстемный или встроенный браузер
end note
Пользователь -> Auth: 3. Запрос страницы авторизации
Auth --> Пользователь: 4. Страница авторизации
note right of Auth
 Если пользователь не аутентифицирован,
 то сначала выполнится его аутентификация
end note
Пользователь -> Auth: 5. Подтверждение доступа
note right of Auth
создаётся код авторизации
сохраняются данные авторизации, которые будут в дальнейшем проверяться
end note
Auth --> Пользователь: 6. Код авторизации (перенаправление обратно на клиента)
note right of Пользователь
 Если приложение нативное, то оно откроется
end note
Пользователь -> Client_app: 7. Код авторизации
Client_app -> Auth: 8. Запрос ключа доступа
Auth --> Client_app: 9. Ключи доступа

Client_app -> Calendar: 10. Добавить событие в календарь
note right of Client_app
 Код доступа в дальнейшем можно использовать для того чтобы обращаться к серверу ресурсов
 и для того, чтобы обновлять ключ доступа при помощи рефреш токена.
end note

@enduml